import { CustomMarketInfo, MarketInfo } from "./types";

// export const customMarketsList: CustomMarketInfo[] = [
//   {
//     address: "GREiyoFSEM7zMce3VugkCggdUYXVK5MijJgGwn7DkVPF",
//     name: "ETHBULL/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "ETHBULL",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "J2eCTuKaABG91kCzJset2UfQRoggHcY2Cq7Stu7natXr",
//     name: "IBVOL/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "IBVOL",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "EnDY66AMMan9FFntp2nNrLW8E8qsXK9Cxi6GZ5QCgRXz",
//     name: "BCHBULL/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "BCHBULL",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "7ygqNwjA94Qu8YKxB8j2ePXYEFyWLcYGUUCVzV9puAhJ",
//     name: "MAPSPOOL/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "MAPSPOOL",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "G1uoNqQzdasMUvXV66Eki5dwjWv5N9YU8oHKJrE4mfka",
//     name: "OXYPOOL/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "OXYPOOL",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "3V2sfA9rCnBwjfqGca2UDxD4fVvPXW9GNAQCqAepKC9Q",
//     name: "RAYPOOL/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "RAYPOOL",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "CjsuF2gB28KqgniogCbbpp7FDMBwAkTawEN3gYKsgfS8",
//     name: "SECO/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SECO",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "9MFFsTVgw6gKPZ1rpc6CSJSLaiNAonChcS7zCCMrAwEP",
//     name: "CEL/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "CEL",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "GJWnwZJ599xjf7cRPP93aaVKqD5xUG5PBLNypHgPxitF",
//     name: "PAXG/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "PAXG",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "E6umfgnsastaGANjpvzb15jaXdZH1wsg4ENHARgbjqUz",
//     name: "GRT/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "GRT",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "QzB9DfWbNAUpfkwLNMLGfkK1AM2zttkMYGSwx5iCnGe",
//     name: "HOLY/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "HOLY",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "4FPFh1iAiitKYMCPDBmEQrZVgA1DVMKHZBU2R7wjQWuu",
//     name: "LQID/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "LQID",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "7AHAKkL94Mx2VAkQb2kk74oNsxDnQ6aab4XwKwisfFdB",
//     name: "PERP/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "PERP",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "CAww1itfT8rFeTCJCLZqTq9anZ7FpC8NzULNLcJMG4Qa",
//     name: "AAVE/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "AAVE",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "Dbyf1PPrAXfMe1LdEq57QW9GY1D4nNEt2fKVGEo6S3MU",
//     name: "COMP/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "COMP",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "2xiv8A5xrJ7RnGdxXB42uFEkYHJjszEhaJyKKt4WaLep",
//     name: "RAY/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "RAY",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "Cm4MmknScg7qbKqytb1mM92xgDxv3TNXos4tKbBqTDy7",
//     name: "RAY/SRM",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "RAY",
//     quoteLabel: "SRM",
//   },
//   {
//     address: "6jx6aoNFbmorwyncVP5V5ESKfuFc9oUYebob1iF6tgN4",
//     name: "RAY/ETH",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "RAY",
//     quoteLabel: "ETH",
//   },
//   {
//     address: "C6tp2RVZnxBPFbnAsfTjis8BN9tycESAT4SgDQgbbrsA",
//     name: "RAY/SOL",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "RAY",
//     quoteLabel: "SOL",
//   },
//   {
//     address: "3BqiaptVkdDCJWz3gea31z1tC3qYfBktUffrSjXjYHWy",
//     name: "IBVOL/USDT",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "IBVOL",
//     quoteLabel: "USDT",
//   },
//   {
//     address: "9wH4Krv8Vim3op3JAu5NGZQdGxU8HLGAHZh3K77CemxC",
//     name: "FIDA/RAY",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "FIDA",
//     quoteLabel: "RAY",
//   },
//   {
//     address: "Fcxy8qYgs8MZqiLx2pijjay6LHsSUqXW47pwMGysa3i9",
//     name: "KIN/RAY",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "KIN",
//     quoteLabel: "RAY",
//   },
//   {
//     address: "HcVjkXmvA1815Es3pSiibsRaFw8r9Gy7BhyzZX83Zhjx",
//     name: "OXY/RAY",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "OXY",
//     quoteLabel: "RAY",
//   },
//   {
//     address: "7Q4hee42y8ZGguqKmwLhpFNqVTjeVNNBqhx8nt32VF85",
//     name: "MAPS/RAY",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "MAPS",
//     quoteLabel: "RAY",
//   },
//   {
//     address: "4Sg1g8U2ZuGnGYxAhc6MmX9MX7yZbrrraPkCQ9MdCPtF",
//     name: "ROPE/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "ROPE",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "97qCB4cAVSTthvJu3eNoEx6AY6DLuRDtCoPm5Tdyg77S",
//     name: "STEP/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "STEP",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "6xC1ia74NbGZdBkySTw93wdxN4Sh2VfULtXh1utPaJDJ",
//     name: "YFI/SRM",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "YFI",
//     quoteLabel: "SRM",
//   },
//   {
//     address: "CDvQqnMrt9rmjAxGGE6GTPUdzLpEhgNuNZ1tWAvPsF3W",
//     name: "FTT/SRM",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "FTT",
//     quoteLabel: "SRM",
//   },
//   {
//     address: "HfsedaWauvDaLPm6rwgMc6D5QRmhr8siqGtS6tf2wthU",
//     name: "BTC/SRM",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "BTC",
//     quoteLabel: "SRM",
//   },
//   {
//     address: "FGYAizUhNEC9GBmj3UyxdiRWmGjR3TfzMq2dznwYnjtH",
//     name: "SUSHI/SRM",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SUSHI",
//     quoteLabel: "SRM",
//   },
//   {
//     address: "FafaYTnhDbLAFsr5qkD2ZwapRxaPrEn99z59UG4zqRmZ",
//     name: "LINK/SRM",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "LINK",
//     quoteLabel: "SRM",
//   },
//   {
//     address: "FR3SPJmgfRSKKQ2ysUZBu7vJLpzTixXnjzb84bY3Diif",
//     name: "SAMO/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SAMO",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "FfiqqvJcVL7oCCu8WQUMHLUC2dnHQPAPjTdSzsERFWjb",
//     name: "MEDIA/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "MEDIA",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "8GufnKq7YnXKhnB3WNhgy5PzU9uvHbaaRrZWQK6ixPxW",
//     name: "TULIP/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "TULIP",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "GqQLxU1Dc6a7NYWRWdgbcGSTHirjy4quFivxXJGDzDCz",
//     name: "MERPOOL/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "MERPOOL",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "GekRdc4eD9qnfPTjUMK5NdQDho8D9ByGrtnqhMNCTm36",
//     name: "SLIM/SOL",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SLIM",
//     quoteLabel: "SOL",
//   },
//   {
//     address: "Eg35DZcYLx6JvZfrEAWgDPfSXJbx2N7hbEwVD56RiXnk",
//     name: "SNYPOOL/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SNYPOOL",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "GX26tyJyDxiFj5oaKvNB9npAHNgdoV9ZYHs5ijs5yG2U",
//     name: "APEX/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "APEX",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "FLKUQGh9VAG4otn4njLPUf5gaUPx5aAZ2Q6xWiD3hH5u",
//     name: "LIQ/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "LIQ",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "7gZNLDbWE73ueAoHuAeFoSu7JqmorwCLpNTBXHtYSFTa",
//     name: "CCAI/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "CCAI",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "Cud48DK2qoxsWNzQeTL5D8sAiHsGwG8Ev1VMNcYLayxt",
//     name: "FAB/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "FAB",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "8N1KkhaCYDpj3awD58d85n973EwkpeYnRp84y1kdZpMX",
//     name: "ORCA/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "ORCA",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "Aubv1QBFh4bwB2wbP1DaPW21YyQBLfgjg8L4PHTaPzRc",
//     name: "SUNNY/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SUNNY",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "7MmPwD1K56DthW14P1PnWZ4zPCbPWemGs3YggcT1KzsM",
//     name: "BOP/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "BOP",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "2Si6XDdpv5zcvYna221eZZrsjsp5xeYoz9W1TVdMdbnt",
//     name: "FROG/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "FROG",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "CwK9brJ43MR4BJz2dwnDM7EXCNyHhGqCJDrAdsEts8n5",
//     name: "WOOF/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "WOOF",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "FhiqrjSsQuEEe2FUMxzkwFadsAwA9ea9YMJLivEFKFbQ",
//     name: "sCAT/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "sCAT",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "7MtgLYSEgsq626pvcEAwaDqs2KiZsaJUX2qGpRZbcDWY",
//     name: "DGEN/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "DGEN",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "4zffJaPyeXZ2wr4whHgP39QyTfurqZ2BEd4M5W6SEuon",
//     name: "SOLAPE/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SOLAPE",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "9fe1MWiKqUdwift3dEpxuRHWftG72rysCRHbxDy6i9xB",
//     name: "CATO/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "CATO",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "9G2bAA5Uv8JyPZteuP73GJLUGg5CMbhMLCRSBUBLoXyt",
//     name: "SHBL/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SHBL",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "HSpeWWRqBJ4HH2FPyfDhoN1AUq3gYoDenQGZASSqzYW1",
//     name: "MOLA/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "MOLA",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "HSfEpP3ciPBC5bBdtjBDa8BxsUW32zUzRGLPpPuDyVY4",
//     name: "SLIM/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SLIM",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "6hwK66FfUdyhncdQVxWFPRqY8y6usEvzekUaqtpKEKLr",
//     name: "SAIL/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SAIL",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "4vvPk9cDzYVSs2rygf2gWAhRVo5DFYtFMSgz5FzypCcs",
//     name: "BHOG/SOL",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "BHOG",
//     quoteLabel: "SOL",
//   },
//   {
//     address: "E3U6GzZwQMDXtd7ABdsfxYx6oeLyaeh6dc6Ez91ZXQrG",
//     name: "ACMN/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "ACMN",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "J4oPt5Q3FYxrznkXLkbosAWrJ4rZLqJpGqz7vZUL4eMM",
//     name: "NINJA/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "NINJA",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "BeF2PKq2jmTJraWEhP28H8BQHUVtuzTyFogtKkxi6D6",
//     name: "LARIX/USDT",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "LARIX",
//     quoteLabel: "USDT",
//   },
//   {
//     address: "CsNZMtypiGgxm6JrmYVJWnLnJNsERrmT3mQqujLsGZj",
//     name: "PRT/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "PRT",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "2Ux1EYeWsxywPKouRCNiALCZ1y3m563Tc4hq1kQganiq",
//     name: "WOO/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "WOO",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "9cuBrXXSH9Uw51JB9odLqEyeF5RQSeRpcfXbEW2L8X6X",
//     name: "SYP/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SYP",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "DNxn3qM61GZddidjrzc95398SCWhm5BUyt8Y8SdKYr8W",
//     name: "ALM/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "ALM",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "Gne8eeLRXF4PgY3N3L2sMsaWDGJgoWZuPDTm7n6p1oe8",
//     name: "MEOW/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "MEOW",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "G3Bss3a2tif6eHNzWCh14g5k2H4rwBAmE42tbckUWG5T",
//     name: "INU/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "INU",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "KrGK6ZHyE7Nt35D7GqAKJYAYUPUysGtVBgTXsJuAxMT",
//     name: "CAVE/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "CAVE",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "Ak1UDskYAjztX5YkxW8dmERjLwS9fYmk1b3G6fpWDxp6",
//     name: "POLE/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "POLE",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "9tr5uMYHgtJ5yG4SeqHA6kJUdzXrK6QCNGYgewQevuuS",
//     name: "BIP/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "BIP",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "7oFXusrpvDzbY6gMM81RjS6YEALETXTwWdUKXXBVojgu",
//     name: "BULL/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "BULL",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "9oCx3vFm5ERDVdjmJHsqE5BJ4eLP4g1aTpf5T4RyRqVy",
//     name: "CKG/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "CKG",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "eju5JDyaf29jYNfq7VrVAocVxGayDEHVHHiM7MYc331",
//     name: "WAGMI/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "WAGMI",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "4M1uP9mYnbraCvw4JuiqFas63K1o74LeoJwpVDW3AAmG",
//     name: "FUM/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "FUM",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "4JP75nztBEo5rYhW1LTQyc4qfjPB33jMWEUvp2DGrQQR",
//     name: "FTR/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "FTR",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "Dvm8jjdAy8uyXn9WXjS2p1mcPeFTuYS6yW2eUL9SJE8p",
//     name: "BOKU/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "BOKU",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "9oXkdAWFyjDH8BbYrDVJ77r6GWPmUWo9ZYYpE25SZ2td",
//     name: "KURO/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "KURO",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "2wgi2FabNsSDdb8dke9mHFB67QtMYjYa318HpSqyJLDD",
//     name: "GOFX/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "GOFX",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "BHqcTEDhCoZgvXcsSbwnTuzPdxv1HPs6Kz4AnPpNrGuq",
//     name: "WAG/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "WAG",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "HYM1HS6MM4E1NxgHPH4Wnth7ztXsYTpbB2Rh9raje8Xq",
//     name: "SOLC/USDT",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SOLC",
//     quoteLabel: "USDT",
//   },
//   {
//     address: "85CTDt8gNfJhmqE3Xm2smDm54HmeT1jvLfPVBTkX8BTX",
//     name: "CAPE/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "CAPE",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "3DEfX1JPAPWKgeBW2XUr7Z1ztNNwbYhhD5EinGC7x1Lf",
//     name: "WEED/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "WEED",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "8pJg7JGfvEfBc14a9wtfAi39doTEeyJHMwqdJrtxsqVx",
//     name: "SINU/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SINU",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "ArKuemtzjpqP5H3P4S21nzhtLZtsq7nMCN6ecA9yvMX9",
//     name: "SCUM/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SCUM",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "6zH7zwXKyTCUFEGGSjzr4ndegLLPGRAhT2mfcWc6wP1w",
//     name: "KINGSHIB/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "KINGSHIB",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "HY9J1nsJxrem6w4uBRaWi2A7iNruNFEooMFopfM584Mv",
//     name: "PART/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "PART",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "91WiupLKLjP8ENihdgiZ53j49aosNm1EYXdLbRD6GAY4",
//     name: "SHIBETOSHI/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SHIBETOSHI",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "9BrQcZ8wMDJ7ibsQKckCd85x5mkqEXL56hnTuvyziPY3",
//     name: "SolBullDog/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "SolBullDog",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "ESd3PskTov69tkW5MmfdV8K7hXR35EXRYorWMNn61dD3",
//     name: "PIXL/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "PIXL",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "HCvX4un57v1SdYQ2LFywaDYyZySqLHMQ5cojq5kQJM3y",
//     name: "RUN/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "RUN",
//     quoteLabel: "USDC",
//   },
//   {
//     address: "9d2NsCGUidYc4b4JD8vc9hbhm1HdTfGpCByUAUakGHCB",
//     name: "MONGOOSE/USDC",
//     programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
//     baseLabel: "MONGOOSE",
//     quoteLabel: "USDC",
//   },
// ];

export const customMarketsList: CustomMarketInfo[] = [
  {
    address: "8BnEgHoWFysVcuFFX7QztDmzuH8r5ZFvyP3sYwn1XTh6",
    name: "SOL/USDC",
    programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
    baseLabel: "SOL",
    quoteLabel: "USDC",
  },
  {
    address: "FZxi3yWkE5mMjyaZj6utmYL54QQYfMCKMcLaQZq4UwnA",
    name: "WETH/USDC",
    programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
    baseLabel: "WETH",
    quoteLabel: "USDC",
  },
  {
    address: "9Lyhks5bQQxb9EyyX55NtgKQzpM4WK7JCmeaWuQ5MoXD",
    name: "mSOL/USDC",
    programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
    baseLabel: "mSOL",
    quoteLabel: "USDC",
  },

  {
    address: "B2na8Awyd7cpC59iEU43FagJAPLigr3AP3s38KM982bu",
    name: "USDT/USDC",
    programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
    baseLabel: "USDT",
    quoteLabel: "USDC",
  },
  {
    address: "8EapfK6wCoRy5sFXZX9gudi8j3m5nLZcuDgxDGWVLgSd",
    name: "CMPN/USDC",
    programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
    baseLabel: "CMPN",
    quoteLabel: "USDC",
  },
  {
    address: "CFW3YFB4uN1NWFDYmcKmT9qA3iyi3L5Bz9QJNjKQAWeS",
    name: "PRT/USDC",
    programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
    baseLabel: "PRT",
    quoteLabel: "USDC",
  },
  {
    address: "72h8rWaWwfPUL36PAFqyQZU8RT1V3FKG7Nc45aK89xTs",
    name: "RLB/USDC",
    programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
    baseLabel: "RLB",
    quoteLabel: "USDC",
  },
  {
    address: "DZjbn4XC8qoHKikZqzmhemykVzmossoayV9ffbsUqxVj",
    name: "RAY/USDC",
    programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
    baseLabel: "RAY",
    quoteLabel: "USDC",
  },
  {
    address: "2AdaV97p6SfkuMQJdu8DHhBhmJe7oWdvbm52MJfYQmfA",
    name: "SOL/USDT",
    programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
    baseLabel: "SOL",
    quoteLabel: "USDT",
  },
  {
    address: "8PhnCfgqpgFM7ZJvttGdBVMXHuU4Q23ACxCvWkbs1M71",
    name: "Bonk/USDC",
    programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
    baseLabel: "Bonk",
    quoteLabel: "USDC",
  },
  {
    address: "BbJgE7HZMaDp5NTYvRh5jZSkQPVDTU8ubPFtpogUkEj4",
    name: "ETH/USDC",
    programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
    baseLabel: "ETH",
    quoteLabel: "USDC",
  },
  {
    address: "3vtRgLDesutQdwotnoUuSMuKKj8YJAE85s938mGKfxXZ",
    name: "scnSOL/USDC",
    programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
    baseLabel: "scnSOL",
    quoteLabel: "USDC",
  },
  {
    address: "BW9gp75QN2DgftnG1Vvu7PbP119EP4xEE5eFXXHkaiea",
    name: "Fronk/USDC",
    programId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
    baseLabel: "Fronk",
    quoteLabel: "USDC",
  },
];
